# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    log.handler:
        class: %monolog.handler.stream.class%
        arguments: [ %kernel.logs_dir%/%kernel.environment%.yourFileName.log ]

    app.util.settings:
        class: AppBundle\Util\Settings
        arguments: [ @doctrine.orm.entity_manager ]
    app.security.user_provider:
        class: AppBundle\Security\UserProvider
        arguments: [ @logger ]
    app.security.pampassword_checker:
        class: AppBundle\Security\PAMPasswordChecker
        arguments: [ @logger ]
    app.security.pamform_authenticator:
        class: AppBundle\Security\PAMFormAuthenticator
        arguments: [ @app.security.pampassword_checker ]


#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
